{
    "_Type": "Action.Type.ApplicationUpdate",
    "ActionResult": {
        "_Name": "AppUpdate"
    },
    "OnFailure": "/MDKAPP/Rules/AppUpdateFailure.js",
    "OnSuccess": "/MDKAPP/Rules/AppUpdateSuccess.js"
}